# Generated by Django 4.2.15 on 2024-08-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
