# Generated by Django 4.2.15 on 2024-08-29 18:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_profile_selected_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
