# Generated by Django 4.2.15 on 2024-08-29 22:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_profile_selected_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_avatar3',
            field=cloudinary.models.CloudinaryField(default='nnn7jme2crgxnlba6ygb', max_length=255, verbose_name='image'),
        ),
    ]
