# Generated by Django 4.2.15 on 2024-08-29 22:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_profile_selected_avatar3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_avatar2',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/inuqkebcm65yyrfhsmfj', max_length=255, verbose_name='image'),
        ),
    ]
