# Generated by Django 4.2.15 on 2024-08-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='profile_image',
            new_name='about_image',
        ),
    ]
