# Generated by Django 4.2.15 on 2024-08-28 16:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_profile_image_about_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/dbtlsekxl5grhsmhvgok', max_length=255, verbose_name='image'),
        ),
    ]
