# Generated by Django 4.2.15 on 2024-09-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_image',
        ),
    ]
